// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// exp_counts_occu
arma::vec exp_counts_occu(arma::mat obs, arma::ivec no_detects, arma::vec psi, arma::vec p);
RcppExport SEXP _ubms_exp_counts_occu(SEXP obsSEXP, SEXP no_detectsSEXP, SEXP psiSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type no_detects(no_detectsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(exp_counts_occu(obs, no_detects, psi, p));
    return rcpp_result_gen;
END_RCPP
}
// exp_counts_occuRN
arma::vec exp_counts_occuRN(arma::mat obs, arma::ivec Kmin, arma::vec lam, arma::vec r);
RcppExport SEXP _ubms_exp_counts_occuRN(SEXP obsSEXP, SEXP KminSEXP, SEXP lamSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type Kmin(KminSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(exp_counts_occuRN(obs, Kmin, lam, r));
    return rcpp_result_gen;
END_RCPP
}
// simz_pcount
arma::imat simz_pcount(arma::umat y, arma::mat lam_post, arma::cube p_post, unsigned K, arma::uvec Kmin, arma::uvec kvals);
RcppExport SEXP _ubms_simz_pcount(SEXP ySEXP, SEXP lam_postSEXP, SEXP p_postSEXP, SEXP KSEXP, SEXP KminSEXP, SEXP kvalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::umat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lam_post(lam_postSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type p_post(p_postSEXP);
    Rcpp::traits::input_parameter< unsigned >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Kmin(KminSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type kvals(kvalsSEXP);
    rcpp_result_gen = Rcpp::wrap(simz_pcount(y, lam_post, p_post, K, Kmin, kvals));
    return rcpp_result_gen;
END_RCPP
}
// simz_occuRN
arma::imat simz_occuRN(arma::umat y, arma::mat lam_post, arma::cube r_post, unsigned K, arma::uvec Kmin, arma::uvec kvals);
RcppExport SEXP _ubms_simz_occuRN(SEXP ySEXP, SEXP lam_postSEXP, SEXP r_postSEXP, SEXP KSEXP, SEXP KminSEXP, SEXP kvalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::umat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lam_post(lam_postSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type r_post(r_postSEXP);
    Rcpp::traits::input_parameter< unsigned >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type Kmin(KminSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type kvals(kvalsSEXP);
    rcpp_result_gen = Rcpp::wrap(simz_occuRN(y, lam_post, r_post, K, Kmin, kvals));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_stan_fit4colext_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4occu_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4occuRN_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4pcount_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_ubms_exp_counts_occu", (DL_FUNC) &_ubms_exp_counts_occu, 4},
    {"_ubms_exp_counts_occuRN", (DL_FUNC) &_ubms_exp_counts_occuRN, 4},
    {"_ubms_simz_pcount", (DL_FUNC) &_ubms_simz_pcount, 6},
    {"_ubms_simz_occuRN", (DL_FUNC) &_ubms_simz_occuRN, 6},
    {"_rcpp_module_boot_stan_fit4colext_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4colext_mod, 0},
    {"_rcpp_module_boot_stan_fit4occu_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4occu_mod, 0},
    {"_rcpp_module_boot_stan_fit4occuRN_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4occuRN_mod, 0},
    {"_rcpp_module_boot_stan_fit4pcount_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4pcount_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ubms(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
