# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

exp_counts_occu <- function(obs, no_detects, psi, p) {
    .Call(`_ubms_exp_counts_occu`, obs, no_detects, psi, p)
}

exp_counts_occuRN <- function(obs, Kmin, lam, r) {
    .Call(`_ubms_exp_counts_occuRN`, obs, Kmin, lam, r)
}

simz_pcount <- function(y, lam_post, p_post, K, Kmin, kvals) {
    .Call(`_ubms_simz_pcount`, y, lam_post, p_post, K, Kmin, kvals)
}

simz_occuRN <- function(y, lam_post, r_post, K, Kmin, kvals) {
    .Call(`_ubms_simz_occuRN`, y, lam_post, r_post, K, Kmin, kvals)
}

simz_multinom <- function(y, lam_post, p_post, K, Kmin, kvals) {
    .Call(`_ubms_simz_multinom`, y, lam_post, p_post, K, Kmin, kvals)
}

